export const CREDENTIAL_MARKER = "__TUG_CRED__";

const sharedCredentialProbeHelpers = () => [
  "const __tugNormalize = (value: unknown): string | undefined => {",
  "  if (Array.isArray(value)) {",
  "    const first = value.find((entry) => entry != null && String(entry).length > 0);",
  "    return first == null ? undefined : String(first);",
  "  }",
  "  if (value == null) {",
  "    return undefined;",
  "  }",
  "  const normalized = String(value);",
  "  return normalized.length > 0 ? normalized : undefined;",
  "};",
  "const __tugResolveSourceLine = (): number | undefined => {",
  "  const stack = new Error().stack;",
  "  if (!stack) {",
  "    return undefined;",
  "  }",
  "  const stackLines = stack.split(/\\r?\\n/).slice(1);",
  "  for (const frame of stackLines) {",
  "    const specMatch = frame.match(/(?:gen|[^\\s]+\\.spec)\\.ts:(\\d+):(\\d+)/);",
  "    if (specMatch) {",
  "      const line = Number(specMatch[1]);",
  "      if (Number.isFinite(line)) {",
  "        return line;",
  "      }",
  "    }",
  "  }",
  "  return undefined;",
  "};",
  "const __tugEmitCredentialSnapshot = (phase: 'entry' | 'fast-early-return' | 'final', payload: Record<string, string | undefined>) => {",
  "  const envelope = {",
  "    phase,",
  "    line: __tugResolveSourceLine(),",
  "    credentials: payload",
  "  };",
  `  console.log('${CREDENTIAL_MARKER}' + JSON.stringify(envelope));`,
  "};",
  "const __tugBuildEntryCredentialSnapshot = () => ({",
  "  // Fast-path and entry probes must avoid touching locals that may still be in TDZ.",
  "  // @ts-ignore - `filler` is an optional local test fixture in target repos.",
  "  email: typeof filler !== 'undefined' ? __tugNormalize(filler?.employee?.emailAddress) : undefined,",
  "  // @ts-ignore - `filler` is an optional local test fixture in target repos.",
  "  password: typeof filler !== 'undefined' ? __tugNormalize(filler?.employee?.password) : undefined,",
  "  // @ts-ignore - `filler` is an optional local test fixture in target repos.",
  "  accountId: typeof filler !== 'undefined' ? __tugNormalize(filler?.accountId) : undefined,",
  "  // @ts-ignore - `filler` is an optional local test fixture in target repos.",
  "  subscriptionId: typeof filler !== 'undefined' ? __tugNormalize(filler?.subscriptionId) : undefined,",
  "  // @ts-ignore - `filler` is an optional local test fixture in target repos.",
  "  databaseId: typeof filler !== 'undefined' ? __tugNormalize(filler?.databaseId) : undefined,",
  "  // @ts-ignore - `filler` is an optional local test fixture in target repos.",
  "  marketplaceId: typeof filler !== 'undefined' ? __tugNormalize(filler?.marketplaceId) : undefined,",
  "  // @ts-ignore - `filler` is an optional local test fixture in target repos.",
  "  smAccountId: typeof filler !== 'undefined' ? __tugNormalize(filler?.accountId) : undefined",
  "});",
  "const __tugBuildFinalCredentialSnapshot = () => ({",
  "  // @ts-ignore - `filler` is an optional local test fixture in target repos.",
  "  email: typeof filler !== 'undefined' ? __tugNormalize(filler?.employee?.emailAddress) : undefined,",
  "  // @ts-ignore - `filler` is an optional local test fixture in target repos.",
  "  password: typeof filler !== 'undefined' ? __tugNormalize(filler?.employee?.password) : undefined,",
  "  // @ts-ignore - `accountId` and `filler` are optional locals in target repos.",
  "  accountId: typeof accountId !== 'undefined' ? __tugNormalize(accountId) : (typeof filler !== 'undefined' ? __tugNormalize(filler?.accountId) : undefined),",
  "  // @ts-ignore - `filler` is an optional local test fixture in target repos.",
  "  subscriptionId: typeof filler !== 'undefined' ? __tugNormalize(filler?.subscriptionId) : undefined,",
  "  // @ts-ignore - `filler` is an optional local test fixture in target repos.",
  "  databaseId: typeof filler !== 'undefined' ? __tugNormalize(filler?.databaseId) : undefined,",
  "  // @ts-ignore - `marketplaceId` and `filler` are optional locals in target repos.",
  "  marketplaceId: typeof marketplaceId !== 'undefined' ? __tugNormalize(marketplaceId) : (typeof filler !== 'undefined' ? __tugNormalize(filler?.marketplaceId) : undefined),",
  "  // @ts-ignore - `smAccountId`, `accountId`, and `filler` are optional locals in target repos.",
  "  smAccountId: typeof smAccountId !== 'undefined' ? __tugNormalize(smAccountId) : (typeof accountId !== 'undefined' ? __tugNormalize(accountId) : (typeof filler !== 'undefined' ? __tugNormalize(filler?.accountId) : undefined))",
  "});"
];

export const entryCredentialProbeStatements = () => [
  ...sharedCredentialProbeHelpers(),
  "const __tugCredEntry = __tugBuildEntryCredentialSnapshot();",
  "__tugEmitCredentialSnapshot('entry', __tugCredEntry);"
];

export const credentialProbeStatements = () => [
  "const __tugCredFinal = __tugBuildFinalCredentialSnapshot();",
  "__tugEmitCredentialSnapshot('final', __tugCredFinal);"
];

export const earlyReturnCredentialProbeStatements = () => [
  "const __tugShouldReturnEarly = (() => {",
  "  const __tugCred = __tugBuildEntryCredentialSnapshot();",
  "  const __tugHasPrimaryCredentials = Boolean(__tugCred.email) && Boolean(__tugCred.password);",
  "  if (!__tugHasPrimaryCredentials) {",
  "    return false;",
  "  }",
  "  __tugEmitCredentialSnapshot('fast-early-return', __tugCred);",
  "  return true;",
  "})();",
  "if (__tugShouldReturnEarly) {",
  "  return;",
  "}"
];
